[package]
name = "sherwood-events"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
sherwood-core = { path = "../core" }
tokio = { workspace = true }
chrono.workspace = true
serde.workspace = true
rust_decimal.workspace = true
async-trait.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "sync"] }
rust_decimal_macros.workspace = true

[lints]
workspace = true
